apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  trigger.on-completed: |
    - send: [my-custom-template]
  trigger.on-paused: |
    - send: [my-paused-template]
      when: rollout.status.controllerPause != nil and rollout.status.controllerPause

  template.my-custom-template: |
    message: |
      Application details: {{.rollout.metadata.name}}.
  template.my-paused-template: |
    message: |
      Application details: {{.rollout.metadata.name}} is paused
  service.slack: |
    token: $slack-token
  #  Slack based notifier with name mattermost